### ISSUE TITLE
superadmin in ulx and cant do any commands?

### ISSUE THREAD

**Issue by ghost** [Chessnut/hl2rp#116]
not really sure how to set this up in the first place lol

**Comment by russianmtf** [comment]
Nutscript does not support ulx. Ulx is its open script. Also, you just saying 'it don't work help" does not help anyone trying to give you support. You just seem to me like another 12 years old trying to own a gmod server. But here is how to solve your superadmin problem.

1. In order to be a superadmin in ulx you need to open your server console and type "adduser (yoursteamname) superadmin"

**Comment by ghost** [comment]
Really cute. Thanks for the reply. I'm not trying to figure out how to add people to ULX. I really don't care anymore. 

 One. LUA is so easy to code that If I wanted to id make my own game-mode.

Two. I don't playe garrysmod anymore. 

Three. 

> You just seem to me like another 12 years old trying to own a gmod server. But here is how to solve your superadmin problem.

The community is so toxic theirs no reason to make a server.

**Comment by russianmtf** [comment]
Honestly I don't care, I am very doubtful you can even code a hello world print text. Your 3rd statement does not make since, I say you seem like another 12 year trying to make his own server, so you respond the community is so toxic theirs no reason to make a server. So I'm right? You're just some kid who could not set up a simple game-mode that is already preset up. I do agree the player base is cancer, you're or were apart of said cancer.

**Comment by ghost** [comment]
My third statement makes a lot of since. You are proving my point. The community automatically amuses random things that don't make any since at all. If you didn't care about what I was saying then you wouldn't reply. Please don't refer to the community as cancer... Maybe if one of your loved ones dies of cancer you will finally understand why I and a lot of other people don't like it when you call something cancer. PrintMessage( HUD_PRINTTALK, "Oh? Whats this??? I know how to code? what a surprise!" )
